const A = {
    // Get Incomes
    REQ_INCOMES: 'REQ_INCOMES',
    REC_INCOMES: 'REC_INCOMES',
    REC_INCOMES_ERR: 'REC_INCOMES_ERR',
    RESET_INCOMES: 'RESET_INCOMES',

    // Get Incomes
    REQ_ADD_INCOME: 'REQ_ADD_INCOME',
    REC_ADD_INCOME: 'REC_ADD_INCOME',
    REC_ADD_INCOME_ERR: 'REC_ADD_INCOME_ERR',
    RESET_ADD_INCOME: 'RESET_ADD_INCOME',

};

export default A;
