const A = {
    // Get Incomes
    REQ_INCOMES: 'REQ_INCOMES',
    REC_INCOMES: 'REC_INCOMES',
    REC_INCOMES_ERR: 'REC_INCOMES_ERR',
    RESET_INCOMES: 'RESET_INCOMES',

    // Add Income
    REQ_ADD_INCOME: 'REQ_ADD_INCOME',
    REC_ADD_INCOME: 'REC_ADD_INCOME',
    REC_ADD_INCOME_ERR: 'REC_ADD_INCOME_ERR',
    RESET_ADD_INCOME: 'RESET_ADD_INCOME',

    // Remove Income
    REQ_REMOVE_INCOME: 'REQ_REMOVE_INCOME',
    REC_REMOVE_INCOME: 'REC_REMOVE_INCOME',
    REC_REMOVE_INCOME_ERR: 'REC_REMOVE_INCOME_ERR',
    RESET_REMOVE_INCOME: 'RESET_REMOVE_INCOME',

    // Update Income
    REQ_UPDATE_INCOME: 'REQ_UPDATE_INCOME',
    REC_UPDATE_INCOME: 'REC_UPDATE_INCOME',
    REC_UPDATE_INCOME_ERR: 'REC_UPDATE_INCOME_ERR',
    RESET_UPDATE_INCOME: 'RESET_UPDATE_INCOME',


    // Get Expenses
    REQ_EXPENSES: 'REQ_EXPENSES',
    REC_EXPENSES: 'REC_EXPENSES',
    REC_EXPENSES_ERR: 'REC_EXPENSES_ERR',
    RESET_EXPENSES: 'RESET_EXPENSES',

    // Add Expense
    REQ_ADD_EXPENSE: 'REQ_ADD_EXPENSE',
    REC_ADD_EXPENSE: 'REC_ADD_EXPENSE',
    REC_ADD_EXPENSE_ERR: 'REC_ADD_EXPENSE_ERR',
    RESET_ADD_EXPENSE: 'RESET_ADD_EXPENSE',

    // Remove Expense
    REQ_REMOVE_EXPENSE: 'REQ_REMOVE_EXPENSE',
    REC_REMOVE_EXPENSE: 'REC_REMOVE_EXPENSE',
    REC_REMOVE_EXPENSE_ERR: 'REC_REMOVE_EXPENSE_ERR',
    RESET_REMOVE_EXPENSE: 'RESET_REMOVE_EXPENSE',

    // Update Expense
    REQ_UPDATE_EXPENSE: 'REQ_UPDATE_EXPENSE',
    REC_UPDATE_EXPENSE: 'REC_UPDATE_EXPENSE',
    REC_UPDATE_EXPENSE_ERR: 'REC_UPDATE_EXPENSE_ERR',
    RESET_UPDATE_EXPENSE: 'RESET_UPDATE_EXPENSE',


    // Get Savings
    REQ_SAVINGS: 'REQ_SAVINGS',
    REC_SAVINGS: 'REC_SAVINGS',
    REC_SAVINGS_ERR: 'REC_SAVINGS_ERR',
    RESET_SAVINGS: 'RESET_SAVINGS',

    // Add Saving
    REQ_ADD_SAVING: 'REQ_ADD_SAVING',
    REC_ADD_SAVING: 'REC_ADD_SAVING',
    REC_ADD_SAVING_ERR: 'REC_ADD_SAVING_ERR',
    RESET_ADD_SAVING: 'RESET_ADD_SAVING',

    // Remove Saving
    REQ_REMOVE_SAVING: 'REQ_REMOVE_SAVING',
    REC_REMOVE_SAVING: 'REC_REMOVE_SAVING',
    REC_REMOVE_SAVING_ERR: 'REC_REMOVE_SAVING_ERR',
    RESET_REMOVE_SAVING: 'RESET_REMOVE_SAVING',

    // Update Saving
    REQ_UPDATE_SAVING: 'REQ_UPDATE_SAVING',
    REC_UPDATE_SAVING: 'REC_UPDATE_SAVING',
    REC_UPDATE_SAVING_ERR: 'REC_UPDATE_SAVING_ERR',
    RESET_UPDATE_SAVING: 'RESET_UPDATE_SAVING',

};

export default A;
