const A = {
    // Get Incomes
    REQ_INCOMES: 'REQ_INCOMES',
    REC_INCOMES: 'REC_INCOMES',
    REC_INCOMES_ERR: 'REC_INCOMES_ERR',
    RESET_INCOMES: 'RESET_INCOMES',

    // Add Income
    REQ_ADD_INCOME: 'REQ_ADD_INCOME',
    REC_ADD_INCOME: 'REC_ADD_INCOME',
    REC_ADD_INCOME_ERR: 'REC_ADD_INCOME_ERR',
    RESET_ADD_INCOME: 'RESET_ADD_INCOME',

    // Remove Income
    REQ_REMOVE_INCOME: 'REQ_REMOVE_INCOME',
    REC_REMOVE_INCOME: 'REC_REMOVE_INCOME',
    REC_REMOVE_INCOME_ERR: 'REC_REMOVE_INCOME_ERR',
    RESET_REMOVE_INCOME: 'RESET_REMOVE_INCOME',

    // Update Income
    REQ_UPDATE_INCOME: 'REQ_UPDATE_INCOME',
    REC_UPDATE_INCOME: 'REC_UPDATE_INCOME',
    REC_UPDATE_INCOME_ERR: 'REC_UPDATE_INCOME_ERR',
    RESET_UPDATE_INCOME: 'RESET_UPDATE_INCOME',

};

export default A;
