// flow-typed signature: 6122f88731c86c0b506f33bdfd156c89
// flow-typed version: <<STUB>>/react-native-material-ui_v1.19.0/flow_v0.56.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-material-ui'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-material-ui' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-material-ui/src/ActionButton/ActionButton.react' {
  declare module.exports: any;
}

declare module 'react-native-material-ui/src/ActionButton/index' {
  declare module.exports: any;
}

declare module 'react-native-material-ui/src/Avatar/Avatar.react' {
  declare module.exports: any;
}

declare module 'react-native-material-ui/src/Avatar/index' {
  declare module.exports: any;
}

declare module 'react-native-material-ui/src/Badge/Badge.react' {
  declare module.exports: any;
}

declare module 'react-native-material-ui/src/Badge/index' {
  declare module.exports: any;
}

declare module 'react-native-material-ui/src/BottomNavigation/BottomNavigation.react' {
  declare module.exports: any;
}

declare module 'react-native-material-ui/src/BottomNavigation/BottomNavigationAction.react' {
  declare module.exports: any;
}

declare module 'react-native-material-ui/src/BottomNavigation/index' {
  declare module.exports: any;
}

declare module 'react-native-material-ui/src/Button/__test__/Button.test' {
  declare module.exports: any;
}

declare module 'react-native-material-ui/src/Button/Button.react' {
  declare module.exports: any;
}

declare module 'react-native-material-ui/src/Button/index' {
  declare module.exports: any;
}

declare module 'react-native-material-ui/src/Card/Card.react' {
  declare module.exports: any;
}

declare module 'react-native-material-ui/src/Card/index' {
  declare module.exports: any;
}

declare module 'react-native-material-ui/src/Checkbox/Checkbox.react' {
  declare module.exports: any;
}

declare module 'react-native-material-ui/src/Checkbox/index' {
  declare module.exports: any;
}

declare module 'react-native-material-ui/src/Container/__test__/Container.test' {
  declare module.exports: any;
}

declare module 'react-native-material-ui/src/Container/index' {
  declare module.exports: any;
}

declare module 'react-native-material-ui/src/Dialog/Actions.react' {
  declare module.exports: any;
}

declare module 'react-native-material-ui/src/Dialog/Content.react' {
  declare module.exports: any;
}

declare module 'react-native-material-ui/src/Dialog/Dialog.react' {
  declare module.exports: any;
}

declare module 'react-native-material-ui/src/Dialog/DialogDefaultActions.react' {
  declare module.exports: any;
}

declare module 'react-native-material-ui/src/Dialog/DialogStackedActions.react' {
  declare module.exports: any;
}

declare module 'react-native-material-ui/src/Dialog/index' {
  declare module.exports: any;
}

declare module 'react-native-material-ui/src/Dialog/Title.react' {
  declare module.exports: any;
}

declare module 'react-native-material-ui/src/Divider/Divider.react' {
  declare module.exports: any;
}

declare module 'react-native-material-ui/src/Divider/index' {
  declare module.exports: any;
}

declare module 'react-native-material-ui/src/Drawer/Drawer.react' {
  declare module.exports: any;
}

declare module 'react-native-material-ui/src/Drawer/Header.react' {
  declare module.exports: any;
}

declare module 'react-native-material-ui/src/Drawer/HeaderAccount.react' {
  declare module.exports: any;
}

declare module 'react-native-material-ui/src/Drawer/index' {
  declare module.exports: any;
}

declare module 'react-native-material-ui/src/Drawer/Section.react' {
  declare module.exports: any;
}

declare module 'react-native-material-ui/src/Icon/index' {
  declare module.exports: any;
}

declare module 'react-native-material-ui/src/IconToggle/IconToggle.react' {
  declare module.exports: any;
}

declare module 'react-native-material-ui/src/IconToggle/index' {
  declare module.exports: any;
}

declare module 'react-native-material-ui/src/index' {
  declare module.exports: any;
}

declare module 'react-native-material-ui/src/ListItem/index' {
  declare module.exports: any;
}

declare module 'react-native-material-ui/src/ListItem/ListItem.react' {
  declare module.exports: any;
}

declare module 'react-native-material-ui/src/RadioButton/index' {
  declare module.exports: any;
}

declare module 'react-native-material-ui/src/RadioButton/RadioButton.react' {
  declare module.exports: any;
}

declare module 'react-native-material-ui/src/RippleFeedback/index.android' {
  declare module.exports: any;
}

declare module 'react-native-material-ui/src/RippleFeedback/index.ios' {
  declare module.exports: any;
}

declare module 'react-native-material-ui/src/RippleFeedback/index.web' {
  declare module.exports: any;
}

declare module 'react-native-material-ui/src/RippleFeedback/RippleFeedbackAndroid.react' {
  declare module.exports: any;
}

declare module 'react-native-material-ui/src/RippleFeedback/RippleFeedbackIOS.react' {
  declare module.exports: any;
}

declare module 'react-native-material-ui/src/RippleFeedback/RippleFeedbackWeb.react' {
  declare module.exports: any;
}

declare module 'react-native-material-ui/src/Snackbar/index' {
  declare module.exports: any;
}

declare module 'react-native-material-ui/src/Snackbar/Snackbar.react' {
  declare module.exports: any;
}

declare module 'react-native-material-ui/src/styles/__test__/getPlatformElevation.test' {
  declare module.exports: any;
}

declare module 'react-native-material-ui/src/styles/__test__/getTheme.test' {
  declare module.exports: any;
}

declare module 'react-native-material-ui/src/styles/colors' {
  declare module.exports: any;
}

declare module 'react-native-material-ui/src/styles/constants' {
  declare module.exports: any;
}

declare module 'react-native-material-ui/src/styles/getPlatformElevation.android' {
  declare module.exports: any;
}

declare module 'react-native-material-ui/src/styles/getPlatformElevation.ios' {
  declare module.exports: any;
}

declare module 'react-native-material-ui/src/styles/getPlatformElevation.web' {
  declare module.exports: any;
}

declare module 'react-native-material-ui/src/styles/getPlatformElevation.windows' {
  declare module.exports: any;
}

declare module 'react-native-material-ui/src/styles/getTheme' {
  declare module.exports: any;
}

declare module 'react-native-material-ui/src/styles/spacing' {
  declare module.exports: any;
}

declare module 'react-native-material-ui/src/styles/ThemeProvider.react' {
  declare module.exports: any;
}

declare module 'react-native-material-ui/src/styles/themes/light' {
  declare module.exports: any;
}

declare module 'react-native-material-ui/src/styles/typography' {
  declare module.exports: any;
}

declare module 'react-native-material-ui/src/Subheader/__test__/Subheader.test' {
  declare module.exports: any;
}

declare module 'react-native-material-ui/src/Subheader/index' {
  declare module.exports: any;
}

declare module 'react-native-material-ui/src/Subheader/Subheader.react' {
  declare module.exports: any;
}

declare module 'react-native-material-ui/src/Toolbar/__test__/Toolbar.test' {
  declare module.exports: any;
}

declare module 'react-native-material-ui/src/Toolbar/CenterElement.react' {
  declare module.exports: any;
}

declare module 'react-native-material-ui/src/Toolbar/index' {
  declare module.exports: any;
}

declare module 'react-native-material-ui/src/Toolbar/LeftElement.react' {
  declare module.exports: any;
}

declare module 'react-native-material-ui/src/Toolbar/RightElement.react' {
  declare module.exports: any;
}

declare module 'react-native-material-ui/src/Toolbar/Toolbar.react' {
  declare module.exports: any;
}

declare module 'react-native-material-ui/src/utils/__test__/isFunction.test' {
  declare module.exports: any;
}

declare module 'react-native-material-ui/src/utils/index' {
  declare module.exports: any;
}

declare module 'react-native-material-ui/src/utils/isFunction' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-material-ui/index' {
  declare module.exports: $Exports<'react-native-material-ui'>;
}
declare module 'react-native-material-ui/index.js' {
  declare module.exports: $Exports<'react-native-material-ui'>;
}
declare module 'react-native-material-ui/src/ActionButton/ActionButton.react.js' {
  declare module.exports: $Exports<'react-native-material-ui/src/ActionButton/ActionButton.react'>;
}
declare module 'react-native-material-ui/src/ActionButton/index.js' {
  declare module.exports: $Exports<'react-native-material-ui/src/ActionButton/index'>;
}
declare module 'react-native-material-ui/src/Avatar/Avatar.react.js' {
  declare module.exports: $Exports<'react-native-material-ui/src/Avatar/Avatar.react'>;
}
declare module 'react-native-material-ui/src/Avatar/index.js' {
  declare module.exports: $Exports<'react-native-material-ui/src/Avatar/index'>;
}
declare module 'react-native-material-ui/src/Badge/Badge.react.js' {
  declare module.exports: $Exports<'react-native-material-ui/src/Badge/Badge.react'>;
}
declare module 'react-native-material-ui/src/Badge/index.js' {
  declare module.exports: $Exports<'react-native-material-ui/src/Badge/index'>;
}
declare module 'react-native-material-ui/src/BottomNavigation/BottomNavigation.react.js' {
  declare module.exports: $Exports<'react-native-material-ui/src/BottomNavigation/BottomNavigation.react'>;
}
declare module 'react-native-material-ui/src/BottomNavigation/BottomNavigationAction.react.js' {
  declare module.exports: $Exports<'react-native-material-ui/src/BottomNavigation/BottomNavigationAction.react'>;
}
declare module 'react-native-material-ui/src/BottomNavigation/index.js' {
  declare module.exports: $Exports<'react-native-material-ui/src/BottomNavigation/index'>;
}
declare module 'react-native-material-ui/src/Button/__test__/Button.test.js' {
  declare module.exports: $Exports<'react-native-material-ui/src/Button/__test__/Button.test'>;
}
declare module 'react-native-material-ui/src/Button/Button.react.js' {
  declare module.exports: $Exports<'react-native-material-ui/src/Button/Button.react'>;
}
declare module 'react-native-material-ui/src/Button/index.js' {
  declare module.exports: $Exports<'react-native-material-ui/src/Button/index'>;
}
declare module 'react-native-material-ui/src/Card/Card.react.js' {
  declare module.exports: $Exports<'react-native-material-ui/src/Card/Card.react'>;
}
declare module 'react-native-material-ui/src/Card/index.js' {
  declare module.exports: $Exports<'react-native-material-ui/src/Card/index'>;
}
declare module 'react-native-material-ui/src/Checkbox/Checkbox.react.js' {
  declare module.exports: $Exports<'react-native-material-ui/src/Checkbox/Checkbox.react'>;
}
declare module 'react-native-material-ui/src/Checkbox/index.js' {
  declare module.exports: $Exports<'react-native-material-ui/src/Checkbox/index'>;
}
declare module 'react-native-material-ui/src/Container/__test__/Container.test.js' {
  declare module.exports: $Exports<'react-native-material-ui/src/Container/__test__/Container.test'>;
}
declare module 'react-native-material-ui/src/Container/index.js' {
  declare module.exports: $Exports<'react-native-material-ui/src/Container/index'>;
}
declare module 'react-native-material-ui/src/Dialog/Actions.react.js' {
  declare module.exports: $Exports<'react-native-material-ui/src/Dialog/Actions.react'>;
}
declare module 'react-native-material-ui/src/Dialog/Content.react.js' {
  declare module.exports: $Exports<'react-native-material-ui/src/Dialog/Content.react'>;
}
declare module 'react-native-material-ui/src/Dialog/Dialog.react.js' {
  declare module.exports: $Exports<'react-native-material-ui/src/Dialog/Dialog.react'>;
}
declare module 'react-native-material-ui/src/Dialog/DialogDefaultActions.react.js' {
  declare module.exports: $Exports<'react-native-material-ui/src/Dialog/DialogDefaultActions.react'>;
}
declare module 'react-native-material-ui/src/Dialog/DialogStackedActions.react.js' {
  declare module.exports: $Exports<'react-native-material-ui/src/Dialog/DialogStackedActions.react'>;
}
declare module 'react-native-material-ui/src/Dialog/index.js' {
  declare module.exports: $Exports<'react-native-material-ui/src/Dialog/index'>;
}
declare module 'react-native-material-ui/src/Dialog/Title.react.js' {
  declare module.exports: $Exports<'react-native-material-ui/src/Dialog/Title.react'>;
}
declare module 'react-native-material-ui/src/Divider/Divider.react.js' {
  declare module.exports: $Exports<'react-native-material-ui/src/Divider/Divider.react'>;
}
declare module 'react-native-material-ui/src/Divider/index.js' {
  declare module.exports: $Exports<'react-native-material-ui/src/Divider/index'>;
}
declare module 'react-native-material-ui/src/Drawer/Drawer.react.js' {
  declare module.exports: $Exports<'react-native-material-ui/src/Drawer/Drawer.react'>;
}
declare module 'react-native-material-ui/src/Drawer/Header.react.js' {
  declare module.exports: $Exports<'react-native-material-ui/src/Drawer/Header.react'>;
}
declare module 'react-native-material-ui/src/Drawer/HeaderAccount.react.js' {
  declare module.exports: $Exports<'react-native-material-ui/src/Drawer/HeaderAccount.react'>;
}
declare module 'react-native-material-ui/src/Drawer/index.js' {
  declare module.exports: $Exports<'react-native-material-ui/src/Drawer/index'>;
}
declare module 'react-native-material-ui/src/Drawer/Section.react.js' {
  declare module.exports: $Exports<'react-native-material-ui/src/Drawer/Section.react'>;
}
declare module 'react-native-material-ui/src/Icon/index.js' {
  declare module.exports: $Exports<'react-native-material-ui/src/Icon/index'>;
}
declare module 'react-native-material-ui/src/IconToggle/IconToggle.react.js' {
  declare module.exports: $Exports<'react-native-material-ui/src/IconToggle/IconToggle.react'>;
}
declare module 'react-native-material-ui/src/IconToggle/index.js' {
  declare module.exports: $Exports<'react-native-material-ui/src/IconToggle/index'>;
}
declare module 'react-native-material-ui/src/index.js' {
  declare module.exports: $Exports<'react-native-material-ui/src/index'>;
}
declare module 'react-native-material-ui/src/ListItem/index.js' {
  declare module.exports: $Exports<'react-native-material-ui/src/ListItem/index'>;
}
declare module 'react-native-material-ui/src/ListItem/ListItem.react.js' {
  declare module.exports: $Exports<'react-native-material-ui/src/ListItem/ListItem.react'>;
}
declare module 'react-native-material-ui/src/RadioButton/index.js' {
  declare module.exports: $Exports<'react-native-material-ui/src/RadioButton/index'>;
}
declare module 'react-native-material-ui/src/RadioButton/RadioButton.react.js' {
  declare module.exports: $Exports<'react-native-material-ui/src/RadioButton/RadioButton.react'>;
}
declare module 'react-native-material-ui/src/RippleFeedback/index.android.js' {
  declare module.exports: $Exports<'react-native-material-ui/src/RippleFeedback/index.android'>;
}
declare module 'react-native-material-ui/src/RippleFeedback/index.ios.js' {
  declare module.exports: $Exports<'react-native-material-ui/src/RippleFeedback/index.ios'>;
}
declare module 'react-native-material-ui/src/RippleFeedback/index.web.js' {
  declare module.exports: $Exports<'react-native-material-ui/src/RippleFeedback/index.web'>;
}
declare module 'react-native-material-ui/src/RippleFeedback/RippleFeedbackAndroid.react.js' {
  declare module.exports: $Exports<'react-native-material-ui/src/RippleFeedback/RippleFeedbackAndroid.react'>;
}
declare module 'react-native-material-ui/src/RippleFeedback/RippleFeedbackIOS.react.js' {
  declare module.exports: $Exports<'react-native-material-ui/src/RippleFeedback/RippleFeedbackIOS.react'>;
}
declare module 'react-native-material-ui/src/RippleFeedback/RippleFeedbackWeb.react.js' {
  declare module.exports: $Exports<'react-native-material-ui/src/RippleFeedback/RippleFeedbackWeb.react'>;
}
declare module 'react-native-material-ui/src/Snackbar/index.js' {
  declare module.exports: $Exports<'react-native-material-ui/src/Snackbar/index'>;
}
declare module 'react-native-material-ui/src/Snackbar/Snackbar.react.js' {
  declare module.exports: $Exports<'react-native-material-ui/src/Snackbar/Snackbar.react'>;
}
declare module 'react-native-material-ui/src/styles/__test__/getPlatformElevation.test.js' {
  declare module.exports: $Exports<'react-native-material-ui/src/styles/__test__/getPlatformElevation.test'>;
}
declare module 'react-native-material-ui/src/styles/__test__/getTheme.test.js' {
  declare module.exports: $Exports<'react-native-material-ui/src/styles/__test__/getTheme.test'>;
}
declare module 'react-native-material-ui/src/styles/colors.js' {
  declare module.exports: $Exports<'react-native-material-ui/src/styles/colors'>;
}
declare module 'react-native-material-ui/src/styles/constants.js' {
  declare module.exports: $Exports<'react-native-material-ui/src/styles/constants'>;
}
declare module 'react-native-material-ui/src/styles/getPlatformElevation.android.js' {
  declare module.exports: $Exports<'react-native-material-ui/src/styles/getPlatformElevation.android'>;
}
declare module 'react-native-material-ui/src/styles/getPlatformElevation.ios.js' {
  declare module.exports: $Exports<'react-native-material-ui/src/styles/getPlatformElevation.ios'>;
}
declare module 'react-native-material-ui/src/styles/getPlatformElevation.web.js' {
  declare module.exports: $Exports<'react-native-material-ui/src/styles/getPlatformElevation.web'>;
}
declare module 'react-native-material-ui/src/styles/getPlatformElevation.windows.js' {
  declare module.exports: $Exports<'react-native-material-ui/src/styles/getPlatformElevation.windows'>;
}
declare module 'react-native-material-ui/src/styles/getTheme.js' {
  declare module.exports: $Exports<'react-native-material-ui/src/styles/getTheme'>;
}
declare module 'react-native-material-ui/src/styles/spacing.js' {
  declare module.exports: $Exports<'react-native-material-ui/src/styles/spacing'>;
}
declare module 'react-native-material-ui/src/styles/ThemeProvider.react.js' {
  declare module.exports: $Exports<'react-native-material-ui/src/styles/ThemeProvider.react'>;
}
declare module 'react-native-material-ui/src/styles/themes/light.js' {
  declare module.exports: $Exports<'react-native-material-ui/src/styles/themes/light'>;
}
declare module 'react-native-material-ui/src/styles/typography.js' {
  declare module.exports: $Exports<'react-native-material-ui/src/styles/typography'>;
}
declare module 'react-native-material-ui/src/Subheader/__test__/Subheader.test.js' {
  declare module.exports: $Exports<'react-native-material-ui/src/Subheader/__test__/Subheader.test'>;
}
declare module 'react-native-material-ui/src/Subheader/index.js' {
  declare module.exports: $Exports<'react-native-material-ui/src/Subheader/index'>;
}
declare module 'react-native-material-ui/src/Subheader/Subheader.react.js' {
  declare module.exports: $Exports<'react-native-material-ui/src/Subheader/Subheader.react'>;
}
declare module 'react-native-material-ui/src/Toolbar/__test__/Toolbar.test.js' {
  declare module.exports: $Exports<'react-native-material-ui/src/Toolbar/__test__/Toolbar.test'>;
}
declare module 'react-native-material-ui/src/Toolbar/CenterElement.react.js' {
  declare module.exports: $Exports<'react-native-material-ui/src/Toolbar/CenterElement.react'>;
}
declare module 'react-native-material-ui/src/Toolbar/index.js' {
  declare module.exports: $Exports<'react-native-material-ui/src/Toolbar/index'>;
}
declare module 'react-native-material-ui/src/Toolbar/LeftElement.react.js' {
  declare module.exports: $Exports<'react-native-material-ui/src/Toolbar/LeftElement.react'>;
}
declare module 'react-native-material-ui/src/Toolbar/RightElement.react.js' {
  declare module.exports: $Exports<'react-native-material-ui/src/Toolbar/RightElement.react'>;
}
declare module 'react-native-material-ui/src/Toolbar/Toolbar.react.js' {
  declare module.exports: $Exports<'react-native-material-ui/src/Toolbar/Toolbar.react'>;
}
declare module 'react-native-material-ui/src/utils/__test__/isFunction.test.js' {
  declare module.exports: $Exports<'react-native-material-ui/src/utils/__test__/isFunction.test'>;
}
declare module 'react-native-material-ui/src/utils/index.js' {
  declare module.exports: $Exports<'react-native-material-ui/src/utils/index'>;
}
declare module 'react-native-material-ui/src/utils/isFunction.js' {
  declare module.exports: $Exports<'react-native-material-ui/src/utils/isFunction'>;
}
