const languageString = {
  np: {
    wallet: 'वालेट',
    income: 'आय',
    expense: 'खर्च',
    saving: 'बचत',
    more: 'अन्य',
    khata: 'खाता',
    inWallet: 'तपाईंको वालेटमा जम्मा',
    language: 'भाषा',
    languageMeta: 'भाषा छनोट गर्नुहोस्',
    currency: 'मुद्रा',
    currencyMeta: 'मुद्रा प्रतिक छनोट गर्नुहोस्',
    rate: 'हामीलाई मूल्याङ्कन गर्नुहोस्',
    rateMeta: 'मूल्याङ्कन दिनुहोस् र हामीलाई समर्थन गर्नुहोस्',
    changeCurrency: 'मुद्रा अङ् अद्यावधिक गर्नुहोस्',
    currencyCode: 'मुद्रा कोड',
    changeLanguage: 'भाषा अद्यावधिक गर्नुहोस्',
    update: 'अद्यावधिक गर्नुहोस्',
    delete: 'मेटाउनुहोस्',
    amount: 'रकम',
    incomeFrom: 'आय भएको',
    addIncome: 'आय थप गर्नुहोस्',
    editIncome: 'आय सम्पादन गर्नुहोस्',
    expenseFrom: 'खर्च भएको',
    addExpense: 'खर्च थप गर्नुहोस्',
    editExpense: 'खर्च सम्पादन गर्नुहोस्',
    savingFrom: 'बचत भएको',
    addSaving: 'बचत थप गर्नुहोस्',
    editSaving: 'बचत सम्पादन गर्नुहोस्'
  },
  hi: {
    wallet: 'बटुआ',
    income: 'आय',
    expense: 'व्यय',
    saving: 'बचत',
    more: 'अधिक',
    khata: 'खाता',
    inWallet: 'अपने बटुए में',
    language: 'भाषा',
    languageMeta: 'अपना पसंदीदा भाषा चुनें',
    currency: 'मुद्रा',
    currencyMeta: 'अपना पसंदीदा मुद्रा प्रतीक चुनें',
    rate: 'हमें रेटिंग दें',
    rateMeta: 'रेटिंग दें और हमें समर्थन दें',
    changeCurrency: 'मुद्रा परिवर्तन करें',
    currencyCode: 'मुद्रा कोड बदलें',
    changeLanguage: 'भाषा बदलो',
    update: 'अद्यतन करें',
    delete: 'इसे मिटाओ',
    amount: 'रकम',
    incomeFrom: 'से आय',
    addIncome: 'आय जोड़ें',
    editIncome: 'आय संपादित करें',
    expenseFrom: 'से खर्च',
    addExpense: 'व्यय जोड़ें',
    editExpense: 'व्यय संपादित करें',
    savingFrom: 'से बचत',
    addSaving: 'बचत जोड़ें',
    editSaving: 'बचत संपादित करें'
  }
};

export default languageString;
